name: Sincronizacion Espejo Google Sheets a Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Esto permite que lo ejecutes manualmente desde el botón "Run workflow"

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Usamos 3.11 para evitar el warning de obsolescencia

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install gspread firebase-admin

      - name: Ejecutar Sincronizador
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python sync_sheets.py
